### ISSUE TITLE
How to update the state on successful completion of operation?

### ISSUE THREAD

**Issue by navneet35371** [klis87/redux-saga-requests#238] opened 2019-03-15 13:00 UTC
I have a editview variable in the state which toggles the view between edit and show. I want to update the value of that after successful completion of update_account operation. How can i do that?

**Comment by klis87** [comment] 2019-03-15 13:17
`import { success, error, abort } from 'redux-saga-requests`;`

You can use those to listen for given response actions of your requets in any reducer.
So, in your case, in reducer responsible for managing `editview`, listen to `success(UPDATE_ACCOUNT)` and update it however you want.

**Comment by navneet35371** [comment] 2019-03-15 13:30
![Screenshot 2019-03-15 at 6 55 46 PM](https://user-images.githubusercontent.com/4524905/54434376-1a904c00-4754-11e9-9f3f-7162427658a4.png)
Thanks for the quick response.  I have done something like this. When i check the redux state diff i get this.
<img width="497" alt="Screenshot 2019-03-15 at 6 58 41 PM" src="https://user-images.githubusercontent.com/4524905/54434513-71962100-4754-11e9-98ea-323ce23f1659.png">

Am i missing something here?

**Comment by klis87** [comment] 2019-03-15 13:48
ok, now I understand the issue, see #231 

the problem is that custom reducer passed as 2nd argument doesn't really get called with all actions. Operation success is one of such a case. The reason is that when I added support to custom reducer which state is then merging with request state, operations weren't even implemented then. 

I could add support to it, but it would make `requestsReducer` implementation unnecessarily complex. so like in #231 , I am actually going to completely remove possibility to pass custom reducer at all. For 2 reasons:
1) I am going to implement even higher level reducer, so you won't need to write `requestsReducer`s at all, actions will be all you need
2) instead of passing custom reducer to `requestsReducer`, why just not keep this it as sibling of `requestsReducer`? You could even use `combineReducers` from redux for such a purpose. And if you want to have this state really merged, you could always use `reselect` to merge state from 2 reducers easily, so your React component or any ui you use could have this in one place.

Please let me know what are your thoughts about it.

**Comment by klis87** [comment] 2019-09-01 11:26
Not relevant since `0.26.0` removed possibility to merge remote state with custom reducer. Use selectors/local mutations instead.

**Closed by klis87** 2019-09-01 11:26 UTC
Labels: question
